### ISSUE TITLE
Add eslint rule for spaces within object brackets like imports

### ISSUE THREAD

**Issue by marzn** [PatternPedia/pattern-pedia-views-ui#51]
We should define if we want to have spaces within object brackets or not. As result we should add `'object-curly-spacing': ['error', 'always'],` or some detailed definition to `.eslintrc.js` like described in https://eslint.org/docs/rules/object-curly-spacing

@manuwei whats you opinion on this?

**Comment by manuwei** [comment]
@marzn I think it's a great idea to add a rule for it. I do not have a preference regarding the options: Go ahead and choose your favorite style!
